### ISSUE TITLE
Why did CHICKEN cross the road?

### ISSUE THREAD

**Issue by Baughn** [danluu/debugging-stories#11]
There should be a link to this epic story of scheming, betrayal, and decompilation of a CHICKEN program.

Unfortunately the only one I've got is http://www.nnl-labs.com/cblog/index.php?/archives/2-Why-Did-CHICKEN-Cross-the...-oh-nevermind.html, which has since disappeared. Anyone got a copy?

**Comment by JesseWeinstein** [comment]
Found it. While the only copy of that URL in the Wayback Machine is oddly empty, there is a copy of the front page of the blog (from some years earlier) that includes the full text of the post (although you have to scroll down) https://web.archive.org/web/20080627131350/http://www.nnl-labs.com/cblog/index.php
