### ISSUE TITLE
The 500 mile email

### ISSUE THREAD

**Issue by vk2sky** [danluu/debugging-stories#19]
I suggest adding this classic (true) story: http://www.ibiblio.org/harris/500milemail.html

**Comment by kevin-brown** [comment]
That's already in there, under the name "The case of the 500-mile email".

**Comment by vk2sky** [comment]
Hi Kevin,

> On 26 Aug 2015, at 10:44 am, Kevin Brown <notifications@github.com> wrote:
> 
> That's already in there, under the name "The case of the 500-mile email".
> 
OK, thanks. I’ll go and get my glasses checked :-)

Cheers,
Richard

**Comment by danluu** [comment]
Tagging this as a dup of #5 just to keep track of dups. Don't mind me :smiley_cat: .
