### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mcastellini** [danluu/debugging-stories#3]
Hi,

I've found a couple of broken links:
 * http://drewdevault.com/2014/02/02/The-worst-bugs.html returns a 302, redirecting to the wrong page; it should be replaced with http://www.drewdevault.com/2014/02/02/The-worst-bugs.html.
 * http://www.cs.bell-labs.com/cm/cs/pearls/sec0510.html returns a 404, there seem to be no alternative URLs.

**Comment by danluu** [comment]
Hmm, Bell labs is preventing web.archive.org from archiving anything via its robots.txt:
~~~
# robots.txt for ftp://plan9.bell-labs.com and http://plan9.bell-labs.com
# see  http://web.nexor.co.uk/mak/doc/robots/norobots.html
# and  http://www.conman.org/people/spc/robots2.html
#
# put recently-added features last in case they cause
# the reader to stop reading.
# Visit-time is a GMT time range of allowed access.
# Request-rate for us is a maximum of one page per 5 seconds, at all hours.
# Crawl-delay is apparently only for msnbot.
#
User-agent: Googlebot
User-agent: msnbot
# the corporate crawler
User-agent: LSgsa-crawler
Disallow: /RealAudio/
Disallow: /bl-traces/
Disallow: /fast-os/
Disallow: /hidden/
Disallow: /historic/
Disallow: /incoming/
Disallow: /inferno/
Disallow: /magic/
Disallow: /netlib.depend/
Disallow: /netlib/
Disallow: /p9trace/
Disallow: /plan9/sources/
Disallow: /sources/
Disallow: /tmp/
Disallow: /tripwire/
Visit-time: 0700-1200
Request-rate: 1/5
Crawl-delay: 5

User-agent: *
Disallow: /
#
# Also, note that the prefixes  ftp:// and http://  lead to the
# same files. 
#
# the following are aliases for the same machine.
#	cm.bell-labs.com
#	cs.bell-labs.com
#	netlib.bell-labs.com
#	outside.cs.bell-labs.com
#	plan9.bell-labs.com
#	plan9.cs.bell-labs.com
#	www.cs.bell-labs.com
~~~

I believe msnbot is now bingbot, so every search engine except for Google is banned from bell labs, too.

Welp, in any case, I wonder if I should start mirroring these things when I link to them. I'll fix the links, but both of those links worked when I added them, and I expect that more links will stop working over time.

**Comment by danluu** [comment]
Took me a while, but I finally fixed this. Thanks! :+1:
